# Generated by Django 5.1.4 on 2025-06-23 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=100)),
                ('nombre_documento', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='documentos_empleado/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.empleado')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_anterior', models.CharField(max_length=100)),
                ('estado_anterior', models.CharField(max_length=100)),
                ('area_nueva', models.CharField(max_length=100)),
                ('estado_nuevo', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('fecha_movimiento', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.empleado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionesJerarquicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinados', to='clinic_master_app.empleado')),
                ('subordinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jefes', to='clinic_master_app.empleado')),
            ],
        ),
    ]
