# Generated by Django 5.1.4 on 2025-06-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentosempleado',
            old_name='id_empleado',
            new_name='empleado',
        ),
        migrations.RemoveField(
            model_name='documentosempleado',
            name='nombre_documento',
        ),
        migrations.AddField(
            model_name='documentosempleado',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentosempleado',
            name='tipo_documento',
            field=models.CharField(choices=[('hoja_vida', 'Hoja de Vida'), ('cedula', 'Cédula'), ('certificado_estudios', 'Certificado de Estudios')], max_length=50),
        ),
    ]
