# Generated by Django 5.2.3 on 2025-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0002_documentosempleado_historialmovimientos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
