# Generated by Django 5.1.4 on 2025-06-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0002_rename_id_empleado_documentosempleado_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='id_empleado',
        ),
        migrations.AddField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.empleado', unique=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(choices=[('temporal', 'Temporal'), ('indefinido', 'Indefinido'), ('practicas', 'Prácticas')], max_length=100),
        ),
    ]
