# Generated by Django 5.2.3 on 2025-06-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0003_cargo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='puesto_empresa',
            field=models.CharField(choices=[('it', 'IT'), ('usuario', 'Usuario'), ('medico', 'Médico'), ('admin', 'Administrador'), ('persona', 'persona'), ('auxiliar', 'Auxiliar')], default='it', max_length=50),
        ),
    ]
