# Generated by Django 5.1.4 on 2025-04-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0003_alter_usuario_puesto_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesis',
            name='medicamentos',
            field=models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('acetaminofen', 'Acetaminofén'), ('ibuprofeno', 'Ibuprofeno'), ('amoxicilina', 'Amoxicilina'), ('loratadina', 'Loratadina'), ('omeprazol', 'Omeprazol'), ('salbutamol', 'Salbutamol'), ('metformina', 'Metformina'), ('losartán', 'Losartán'), ('enalapril', 'Enalapril')], default='ninguno', max_length=50, null=True),
        ),
    ]
