# Generated by Django 5.1.4 on 2025-06-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0003_remove_contrato_id_empleado_contrato_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='documento_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.empleado'),
        ),
    ]
