# Generated by Django 5.1.4 on 2025-04-18 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0004_alter_anamnesis_medicamentos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='id_examen',
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
    ]
