# Generated by Django 5.1.4 on 2025-04-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0005_remove_diagnostico_id_examen_delete_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='fecha_expiracion',
            field=models.DateField(),
        ),
    ]
