# Generated by Django 4.2.6 on 2025-04-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0006_alter_formula_fecha_expiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('Ninguno', 'ninguno'), ('Medicina General', 'Atención médica básica'), ('Cardiología', 'Enfermedades del corazón'), ('Neumología', 'Enfermedades respiratorias'), ('Gastroenterología', 'Trastornos digestivos'), ('Dermatología', 'Enfermedades de la piel'), ('Pediatría', 'Atención a niños y adolescentes'), ('Obstetricia y Ginecología', 'Salud femenina y embarazo'), ('Neurología', 'Enfermedades del sistema nervioso'), ('Oncología', 'Tratamiento del cáncer'), ('Psiquiatría', 'Trastornos mentales y emocionales'), ('Cirugía General', 'Intervenciones quirúrgicas comunes'), ('Ortopedia', 'Trastornos del sistema musculoesquelético'), ('Oftalmología', 'Enfermedades de los ojos'), ('Radiología', 'Diagnóstico por imágenes'), ('Anestesiología', 'Anestesia en procedimientos quirúrgicos')], max_length=100),
        ),
    ]
