# Generated by Django 4.2.6 on 2025-04-22 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0007_alter_cita_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_master_app.sala'),
        ),
    ]
