# Generated by Django 4.2.6 on 2025-04-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_master_app', '0008_cita_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='horario_disponible',
        ),
        migrations.AddField(
            model_name='sala',
            name='disponibilidad_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='disponibilidad_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
